# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Rookery - Web Design and Development
email: amandasaffer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Rookery specializes in web design, web development,
  and logo design. We help small businesses and entrepreneurs bring 
  their ideas to life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rkry.io" # the base hostname & protocol for your site
twitter_username: ajsaffer
github_username:  amandasaffer

collections:
  cases:
    output: true
    title: cases
    permalink: /cases/:path/

# Build settings
markdown: kramdown
